Repository RollingPaper42/Front-End, pull requests merged in 2023-12, with the labels that each got.

#167 [Fix] Drawer 추가 기능 및 변경사항 반영
  src/app/globals.css
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Drawer.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/DrawerItem.tsx
  src/component/HeaderLayout/DropList.tsx
  src/component/HeaderLayout/DropListItem.tsx
  src/component/HeaderLayout/index.tsx
  src/types/drawerBoard.ts
Labels: 🔨 fix, ✨ feature

#171 [Fix] Add component 버그 해결 및 디자인 변경사항 반영
  src/component/Add.tsx
  src/component/PhotoUpload.tsx
Labels: 🔨 fix, 🎨 style

#173 [Style] summary 페이지 테마 적용
  src/app/group/[id]/summary/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/SummaryBoard.tsx
  src/recoil/theme.ts
Labels: ♻️ refactor, 🎨 style

#169 Fix/highlight bug#163
  src/app/personal/[id]/page.tsx
  src/component/ObserveContent.tsx
  src/component/StrcatBoard.tsx
Labels: 🐞 bug, 🔨 fix

#174 [Fix] 모달디자인 수정 및 그룹페이지 추가 요구사항 수정
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Add.tsx
  src/component/BottomButton.tsx
  src/component/GroupMainTitle.tsx
  src/component/HeaderLayout/DropList.tsx
  src/component/Icon/ModalBackground.tsx
  src/component/Icon/ShareModal.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/Modal/ExportSuccess.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatGroupTitle.tsx
  src/recoil/theme.ts
Labels: 🔨 fix

#179 [feat]overscoll#178
  src/app/layout.tsx
Labels: ✨ feature

#177 [Fix] window type error#163
  src/app/personal/[id]/page.tsx
Labels: 🐞 bug, 1️⃣ first issue

#176 [fix]backheader 컴포넌트 적용
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/app/group/[id]/export/page.tsx
  src/app/personal/[id]/export/page.tsx
Labels: 🔨 fix

#183 [HotFix] font 모음 unicode적용 #162
  src/app/globals.css
Labels: 🔨 fix

#188 [Refactor]font_theme 전역 적용#186
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/group/[id]/summary/page.tsx
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/Add.tsx
  src/component/BottomButton.tsx
  src/component/GroupMainTitle.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/Modal/ExportSuccess.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/PhotoUpload.tsx
  src/component/ShareButton.tsx
  src/component/StrcatGroupTitle.tsx
  src/component/SummaryBoard.tsx
  src/component/export/ExportBoard.tsx
  src/recoil/font.ts
  tailwind.config.js
Labels: ♻️ refactor

#190 [Fix] drawer 드래그 불가능하게 변경 #189
  src/component/HeaderLayout/DrawerItem.tsx
  src/component/HeaderLayout/DropListItem.tsx
Labels: 🔨 fix

#193 [Feat] inapp browser 비활성화
  src/app/InApp.tsx
  src/app/layout.tsx
Labels: ✨ feature

#191 [Refactor]테마 리팩토링 및 전체 적용#185
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/group/[id]/summary/page.tsx
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/Add.tsx
  src/component/GroupMainTitle.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/DropList.tsx
  src/component/HeaderLayout/DropListItem.tsx
  src/component/Loading.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/PhotoUpload.tsx
  src/component/ShareButton.tsx
  src/component/StrcatGroupTitle.tsx
  src/component/ThemeChange.tsx
  src/component/export/ExportBoard.tsx
  src/recoil/IconTheme.ts
  src/recoil/bgTheme.ts
  src/recoil/textTheme.ts
  src/recoil/theme.ts
Labels: ♻️ refactor

#200 [Refactor]prettier을 활용한 import 정렬#196
  package-lock.json
  package.json
  prettier.config.js
  src/app/create/group/page.tsx
  tsconfig.json
Labels: ♻️ refactor

#199 [feat] og ,타이틀, 파비콘 적용 #198
  public/Favicon.png
  public/OG.png
  src/app/layout.tsx
  src/component/OpenGraph.tsx
Labels: ✨ feature

#203 [Refactor] recoilstate 상단으로 Inapp 태그 이동#202
  src/app/layout.tsx
  src/component/ThemeChange.tsx
  src/utils/axios.ts
Labels: ♻️ refactor

#205 [refactor] z-index설정, theme디렉토리 설정
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/group/[id]/summary/page.tsx
  src/app/login/page.tsx
  src/app/modal/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/Add.tsx
  src/component/CatAnimation.tsx
  src/component/GroupMainTitle.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/DropList.tsx
  src/component/HeaderLayout/DropListItem.tsx
  src/component/Loading.tsx
  src/component/Modal/index.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/PhotoUpload.tsx
  src/component/ShareButton.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatGroupTitle.tsx
  src/component/ThemeChange.tsx
  src/component/export/ExportBoard.tsx
  src/hooks/useCat.ts
  src/recoil/state.ts
  src/recoil/theme/IconTheme.ts
  src/recoil/theme/bgTheme.ts
  src/recoil/theme/catAnimation.ts
  src/recoil/theme/catTheme.ts
  src/recoil/theme/textTheme.ts
  src/recoil/theme/theme.ts
  tailwind.config.js
Labels: ♻️ refactor

#214 [Refactor] inApp refactoring #213
  src/app/InApp.tsx
Labels: ♻️ refactor

#210 [Refactor]observe content#209
  package-lock.json
  package.json
  src/app/group/[id]/page.tsx
  src/app/login/check/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/ContentPhoto.tsx
  src/component/ObserveContent.tsx
  src/component/StrcatBoard.tsx
  src/types/observe.ts
Labels: 🐞 bug, 🔨 fix, ♻️ refactor

#206 [refactor] 버튼 css 수정#204
  public/Download.svg
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/Add.tsx
  src/component/BottomButton.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/Modal/ExportSuccess.tsx
  src/recoil/theme/bgTheme.ts
  tailwind.config.js
Labels: ♻️ refactor

#211 [feat] toast 생성
  src/app/toast/page.tsx
  src/component/Toast.tsx
  tailwind.config.js
Labels: ✨ feature

#216 [Refactor] photoUpload logic 간소화
  src/app/modal/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/Add.tsx
  src/component/PhotoUpload.tsx
Labels: ♻️ refactor

#227 [Feat] header변경사항 적용
  src/app/create/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/TitleHeader.tsx
  src/component/HeaderLayout/index.tsx
  src/component/Icon/Header.tsx
  src/component/Icon/header/HamburgerMenu.tsx
  src/recoil/state.ts
  src/recoil/title.ts
Labels: ✨ feature, ♻️ refactor

#228 [Feat] textarea component#225
  src/app/create/page.tsx
  src/component/Textarea.tsx
  tailwind.config.js
Labels: ✨ feature

#233 [Feat]personal page 첫 문장, 마음 확인 워딩 #231
  src/app/personal/[id]/NoneContent.tsx
  src/app/personal/[id]/Summary.tsx
  src/app/personal/[id]/page.tsx
  src/component/ObserveContent.tsx
  src/component/StrcatBoard.tsx
Labels: ✨ feature

#235 [Feat] : add컴포넌트를 페이지로 변경
  public/Delete.svg
  src/app/personal/[id]/add/page.tsx
  src/component/Add.tsx
  src/component/BottomButton.tsx
  src/component/HeaderLayout/TitleHeader.tsx
  src/component/HeaderLayout/index.tsx
  src/component/Icon/Close.tsx
  src/component/PhotoUpload.tsx
  src/component/PreviewPhoto.tsx
  src/recoil/title.ts
Labels: ✨ feature, 🎨 style

#236 [Feat] picture preview 추가 및 모달 연결#234
  public/PhotoPreview.svg
  src/app/personal/[id]/PhotoPreview.tsx
  src/app/personal/[id]/page.tsx
  src/component/ObserveContent.tsx
  src/component/StrcatBoard.tsx
Labels: ✨ feature

#238 [Fix] picture preview Image tag 에러 #237
  src/app/personal/[id]/PhotoPreview.tsx
Labels: 🐞 bug, 🔨 fix

#239 [Feat] : 스크롤시 Header 숨기는 기능 추가
  src/app/page.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  src/component/HeaderLayout/TitleHeader.tsx
  src/component/Icon/Header.tsx
  src/component/Icon/LongCat.tsx
  src/component/Icon/header/HeaderProfileCat.tsx
  src/component/Icon/header/LogoCat.tsx
  src/component/Icon/header/Outline.tsx
  src/component/Textarea.tsx
  src/hooks/useScroll.tsx
  src/recoil/layoutHidden.ts
Labels: ✨ feature

#242 Feat/메인 페이지, 로그인 페이지. not found 페이지 디자인 변경 #240
  public/404cat.svg
  public/IconNext.svg
  public/IconUnder.svg
  public/StrcatIcon.svg
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/component/MainManStrcat.tsx
Labels: 🎨 style

#247 [Fix] scroll event수정 #246
  src/app/personal/[id]/page.tsx
  src/hooks/useScroll.tsx
Labels: 🔨 fix

#243 [Fix] 포토모달 하이라이트 디자인 수정
  src/component/Modal/PhotoModal.tsx
Labels: 🔨 fix, 🎨 style

#248 [Fix] drawer 에러사항 수정
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/DropList.tsx
  src/component/HeaderLayout/DropListItem.tsx
  src/component/Icon/drawer/Check.tsx
Labels: 🔨 fix

#250 [Feat] highlight focus#245
  src/app/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/ObserveContent.tsx
  src/utils/focusToHighlight.ts
Labels: ✨ feature

#256 [Fix] font woff2 추가 #255
  public/fonts/PretendardVariable.woff2
  src/app/globals.css
Labels: 🔨 fix

#258 [Fix] prettier plugin 버전 변경 #257
  package-lock.json
  package.json
Labels: 🔨 fix

#253 [Feat] 눈내리는 애니메이션 구현 #252
  src/app/personal/[id]/SnowAnimation.tsx
  src/app/personal/[id]/page.tsx
  tailwind.config.js
Labels: ✨ feature

#263 Fix/build error design fix#262
  src/app/personal/[id]/Summary.tsx
  src/app/personal/[id]/page.tsx
Labels: 🐞 bug, 🎨 style

#259 [Feat] modal 생성
  src/app/create/page.tsx
  src/app/modal/page.tsx
  src/app/personal/[id]/add/page.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/index.tsx
  src/component/ObserveContent.tsx
  src/utils/confirm.ts
  tailwind.config.js
Labels: ✨ feature

#264 [Feat]createtheme css 구성#261
  public/chrisCat.svg
  public/masCat.svg
  public/preview/chris.svg
  public/preview/christ.svg
  public/preview/lilac.svg
  public/preview/mas.svg
  public/preview/night.svg
  public/preview/peach.svg
  src/component/CreateTheme.tsx
  tailwind.config.js
Labels: ✨ feature

#272 Feat/add on cat#271
  public/cats/calm/in.gif
  public/cats/calm/leftWall.gif
  public/cats/calm/out.gif
  public/cats/calm/rightWall.gif
  public/cats/calm/sit.gif
  public/cats/christ/sit.gif
  public/cats/cyan/in.gif
  public/cats/cyan/leftWall.gif
  public/cats/cyan/out.gif
  public/cats/cyan/rightWall.gif
  public/cats/cyan/sit.gif
  public/cats/green/in.gif
  public/cats/green/leftWall.gif
  public/cats/green/out.gif
  public/cats/green/rightWall.gif
  public/cats/green/sit.gif
  public/cats/lilac/sit.gif
  public/cats/mas/sit.gif
  public/cats/peach/sit.gif
  public/cats/strcat/in.gif
  public/cats/strcat/leftWall.gif
  public/cats/strcat/out.gif
  public/cats/strcat/rightWall.gif
  public/cats/strcat/sit.gif
  public/cats/yellow/sit.gif
  src/app/create/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/CatAnimation.tsx
  src/component/CreateTheme.tsx
  src/component/GroupMainTitle.tsx
  src/component/MainManStrcat.tsx
  src/component/ThemeChange.tsx
  src/component/export/ExportBoard.tsx
  src/hooks/useCat.ts
  src/recoil/theme/catAnimation.ts
  src/recoil/theme/theme.ts
  src/types/animation.ts
  src/types/boards.ts
Labels: ✨ feature

#268 Fix/content photo display#265
  src/app/personal/[id]/PhotoPreview.tsx
  src/app/personal/[id]/page.tsx
  src/component/ObserveContent.tsx
Labels: 🔨 fix, ✨ feature

#274 [Fix] add페이지 자잘한 수정
  src/app/create/page.tsx
  src/app/personal/[id]/add/Writer.tsx
  src/app/personal/[id]/add/page.tsx
  src/component/HeaderLayout/TitleHeader.tsx
  src/component/Textarea.tsx
Labels: 🔨 fix, ♻️ refactor, 🎨 style

#269 [Feat]loading page#266
  src/app/personal/[id]/page.tsx
  src/component/Loading.tsx
  tailwind.config.js
Labels: ✨ feature

#275 [Fix] photo 모달 디자인 및 오류 수정
  src/component/HeaderLayout/Drawer.tsx
  src/component/Modal/PhotoModal.tsx
  src/component/ObserveContent.tsx
Labels: 🔨 fix, 🎨 style

#279 [Fix] header & [Refactor] create 페이지 & [Fix] snow animation
  public/cats/chris/sit.gif
  public/cats/night/sit.gif
  public/preview/chris.svg
  src/app/api/personal/data.json
  src/app/create/TitleSelect.tsx
  src/app/create/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/SnowAnimation.tsx
  src/app/personal/[id]/layout.tsx
  src/component/CreateTheme.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/TitleHeader.tsx
  src/component/HeaderLayout/index.tsx
  src/component/Icon/Back.tsx
  src/component/Modal/Confirm.tsx
  src/component/SelectButton.tsx
  src/recoil/title.ts
  src/utils/confirm.ts
  src/utils/drawerOpen.tsx
  tailwind.config.js
Labels: 🔨 fix, ♻️ refactor

#280 [Feat] pernoal 페이지 저장, 공유하기 버튼에 토스트 및 기능 적용
  src/app/modal/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/HeaderLayout/DropListItem.tsx
  src/component/ShareButton.tsx
  src/component/Toast.tsx
  src/utils/handleShare.tsx
Labels: ✨ feature

#283 [Rename] 안쓰는 파일 제거 및 아이콘 경로 수정
  public/CalmButton.svg
  public/GreenButton.svg
  public/NotFoundButton.svg
  public/NotFoundCat.svg
  public/Picture.svg
  public/StrcatButton.svg
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/Icon/Header.tsx
  src/component/Icon/ModalBackground.tsx
  src/component/Icon/ModalClose.tsx
  src/component/Icon/ModalErrorBackground.tsx
  src/component/Icon/PhotoClose.tsx
  src/component/Icon/Share.tsx
  src/component/Icon/ShareModal.tsx
  src/component/Icon/ShortCut.tsx
  src/component/Icon/Strcat.tsx
  src/component/Icon/Theme.tsx
  src/component/Icon/header/Back.tsx
  src/component/Icon/header/Logo.tsx
  src/component/Icon/header/LogoText.tsx
  src/component/Icon/themeSelect/ThemeCalm.tsx
  src/component/Icon/themeSelect/ThemeCyan.tsx
  src/component/Icon/themeSelect/ThemeGreen.tsx
  src/component/Icon/themeSelect/ThemeStrcat.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/Modal/ExportSuccess.tsx
  src/component/Modal/PhotoModal.tsx
  src/component/ObserveTitle.tsx
  src/component/StrcatGroupTitle.tsx
  src/component/SummaryBoard.tsx
  src/types/export.ts
Labels: 🧹 cleanup

#286 [Fix] npm run build 에러 해결
  src/app/modal/page.tsx
  src/component/export/Default.tsx
  src/component/export/ExportBoard.tsx
  src/component/export/ExportTheme.tsx
  src/component/export/LineBreak.tsx
  src/component/export/Writer.tsx
Labels: 🔨 fix

#284 [Feat] 에러 모달 디자인
  src/app/create/page.tsx
  src/app/modal/page.tsx
  src/app/personal/[id]/add/page.tsx
  src/component/Modal/Error.tsx
  src/hooks/useInterceptor.tsx
Labels: 🔨 fix, ✨ feature, 🎨 style

#288 [Reafactor]테마 정리#276
  src/recoil/newtheme/bgTheme.ts
  src/recoil/newtheme/default.ts
  src/recoil/newtheme/textTheme.ts
  src/recoil/newtheme/theme.ts
  tailwind.config.js
Labels: ♻️ refactor

#285 [Fix] button select-none 속성 추가
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/NoneContent.tsx
  src/app/personal/[id]/add/Writer.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/BottomButton.tsx
  src/component/CatAnimation.tsx
  src/component/HeaderLayout/DrawerItem.tsx
  src/component/HeaderLayout/DropList.tsx
  src/component/HeaderLayout/DropListItem.tsx
  src/component/HeaderLayout/TitleHeader.tsx
  src/component/MainManStrcat.tsx
  src/component/MiddleButton.tsx
  src/component/Modal/index.tsx
  src/component/ObserveContent.tsx
  src/component/PhotoUpload.tsx
  src/component/SelectButton.tsx
  src/component/StrcatBoard.tsx
  src/component/Textarea.tsx
Labels: 🎨 style

#297 Feat/theme main page#287
  public/theme/chris.svg
  public/theme/mas.svg
  src/app/personal/[id]/SnowAnimation.tsx
  src/app/personal/[id]/page.tsx
  src/component/BottomImage.tsx
Labels: 🔨 fix, ✨ feature, ♻️ refactor

#295 [Fix] Back Button Url #277
  src/app/login/check/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/TitleHeader.tsx
  src/component/HeaderLayout/index.tsx
Labels: 🔨 fix

#301 [Style] design반영 #300
  public/IconNext.svg
  public/LongCat.svg
  public/MainImage.png
  public/MainImage.svg
  public/StrcatIcon.svg
  public/fonts/Sniglet-ExtraBold.ttf
  src/app/globals.css
  src/app/login/page.tsx
  src/app/page.tsx
  src/component/BottomButton.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  tailwind.config.js
Labels: 🎨 style

#307 [Fix] input field whitespace만 넣을경우 #303
  src/app/personal/[id]/add/Writer.tsx
  src/component/Textarea.tsx
Labels: 🔨 fix

#309 [Fix] theme 머지과정에서 생겼던 오류 수정
  src/app/page.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
Labels: 🔨 fix

#305 [Feat] shorten url#304
  src/app/layout.tsx
  src/app/personal/[id]/Summary.tsx
  src/app/personal/[id]/page.tsx
Labels: ✨ feature

#310 [Refactor]create page order change#294
  public/preview/chris.svg
  src/app/create/CreateTheme.tsx
  src/app/create/TitleSelect.tsx
  src/app/create/page.tsx
Labels: ♻️ refactor

#312 [Fix] 조회 페이지에서 부르는 button만 shadow가 들어가도록 변경 #311
  src/app/personal/[id]/page.tsx
  src/component/BottomButton.tsx
Labels: 🔨 fix

#316 fix: 아래 패딩 60% -> 70%로 변경
  src/app/api/personal/data.json
  src/app/personal/[id]/page.tsx
Labels: 🐞 bug, 🔨 fix

#318 [HotFix] UT 수정사항 반영
  public/preview/chris.png
  public/preview/chris.svg
  public/preview/lilac.png
  public/preview/lilac.svg
  public/preview/mas.png
  public/preview/mas.svg
  public/preview/night.png
  public/preview/night.svg
  public/preview/peach.png
  public/preview/peach.svg
  src/app/create/CreateTheme.tsx
  src/app/page.tsx
Labels: 🔨 fix

#321 [Fix] UT 이후 add, create페이지 변경사항 작업 #319
  package-lock.json
  package.json
  public/preview/chris.png
  public/preview/lilac.png
  public/preview/mas.png
  public/preview/night.png
  public/preview/peach.png
  src/app/create/CreateTheme.tsx
  src/app/create/PreviewTheme.tsx
  src/app/create/ThemeSelect.tsx
  src/app/create/TitleSelect.tsx
  src/app/create/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/add/Writer.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/HeaderLayout/index.tsx
  src/component/Loading.tsx
  src/component/PhotoUpload.tsx
  src/component/Textarea.tsx
Labels: 🔨 fix, ♻️ refactor

#323 [Refactor] bottom button props정리 #322
  src/app/create/CreateTheme.tsx
  src/app/create/TitleSelect.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/BottomButton.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/PhotoUpload.tsx
Labels: ♻️ refactor

#324 [Feat] release patch#320
  public/theme/mas.svg
  src/app/create/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/PhotoPreview.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/BottomImage.tsx
  src/component/ContentPhoto.tsx
  src/component/HeaderLayout/DefaultHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/Icon/PhotoPreview.tsx
  src/component/MainManStrcat.tsx
  src/component/Modal/PhotoModal.tsx
  src/component/ObserveContent.tsx
  src/component/StrcatBoard.tsx
  src/recoil/content.ts
  src/recoil/newtheme/theme.ts
  src/recoil/state.ts
  src/types/theme.ts
  src/utils/theme/bgTheme.ts
  src/utils/theme/textTheme.ts
Labels: 🔨 fix, ✨ feature

#326 style : text opacity 제거
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/Toast.tsx
  tailwind.config.js
Labels: 🎨 style

#329 fix: 잘 못 지운 코드 수정: add 페이지 접속 시 헤더 띄우기 #328
  src/app/personal/[id]/page.tsx
  src/component/HeaderLayout/TitleHeader.tsx
Labels: 🔨 fix

#331 [Refactor]font theme apply#296
  src/app/create/TitleSelect.tsx
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/personal/[id]/NoneContent.tsx
  src/app/personal/[id]/Summary.tsx
  src/app/personal/[id]/add/Writer.tsx
  src/app/personal/[id]/add/page.tsx
  src/component/BottomButton.tsx
  src/component/HeaderLayout/BackButtonHeader.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/DrawerItem.tsx
  src/component/HeaderLayout/DropList.tsx
  src/component/MiddleButton.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/Modal/PhotoModal.tsx
  src/component/ObserveContent.tsx
  src/component/SelectButton.tsx
  src/component/Textarea.tsx
  src/recoil/font.ts
Labels: ♻️ refactor

#330 [Feat/Fix] 공유하기 IOS에서 바텀시트 추가
  src/app/personal/[id]/page.tsx
Labels: 🔨 fix, ✨ feature

#333 [HotFix] photo 압축률 변경
  public/create/chrisCat.svg
  public/create/masCat.svg
  public/personal/Download.svg
  public/personal/PhotoPreview.svg
  public/personal/chrisSnowman.svg
  public/personal/masTree.svg
  src/app/create/CreateTheme.tsx
  src/app/create/ThemeSelect.tsx
  src/app/personal/[id]/add/Writer.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/BottomImage.tsx
  src/component/PhotoUpload.tsx
Labels: 🔨 fix

#337 hotfix : 압축실패시 에러모달창 추가
  src/component/Modal/Error.tsx
  src/component/Modal/PhotoModal.tsx
  src/component/PhotoUpload.tsx
Labels: 🔨 fix

#339 [HotFix] : photo compress제발 마지막 패치이길 🙏
  src/component/PhotoUpload.tsx
Labels: 🔨 fix

#338 [Feat] seo를 위한 description 설정, 공유하기 shortenurl제거
  src/app/layout.tsx
  src/app/personal/[id]/NoneContent.tsx
  src/app/personal/[id]/page.tsx
  src/component/Description.tsx
Labels: 🔨 fix, ✨ feature

#344 [Style] cta color#342
  src/app/page.tsx
  src/utils/theme/bgTheme.ts
Labels: 🎨 style

#346 [Fix] Image S3 link 추가
  next.config.js
  src/app/layout.tsx
  src/app/personal/[id]/PhotoPreview.tsx
  src/component/Photo.tsx
Labels: ⚙️ chore

#340 [Feat] mixpanel#335
  package-lock.json
  package.json
  src/app/page.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/PhotoUpload.tsx
  src/services/mixpanel.ts
  src/types/mixpanel.ts
Labels: ✨ feature

#345 [Feat] 개인정보처리방침, 이용약관 페이지 추가
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/privacy/page.tsx
  src/app/terms/page.tsx
  src/component/HeaderLayout/Drawer.tsx
  src/component/HeaderLayout/DropList.tsx
  src/component/Icon/drawer/Inquiry.tsx
Labels: 🔨 fix, ✨ feature

#349 [Refactor]create css fix#347
  src/app/create/TitleSelect.tsx
Labels: ♻️ refactor

#351 [Hotfix] after deploy
  public/preview/chris.png
  public/preview/lilac.png
  public/preview/mas.png
  public/preview/night.png
  public/preview/peach.png
  src/app/create/PreviewTheme.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/component/BottomImage.tsx
  src/component/Loading.tsx
  src/utils/theme/textTheme.ts
Labels: 🔨 fix

#352 [Fix] main bottom padding#348
  src/app/page.tsx
Labels: ✨ feature

#353 [HotFix] Bottom Image 고양이 크기 긴급 패치
  src/component/BottomImage.tsx
Labels: 🎨 style

#354 [Hotfix] bottom button & 조회 페이지 perview image변경
  src/app/personal/[id]/PhotoPreview.tsx
  src/app/personal/[id]/page.tsx
  src/component/OpenGraph.tsx
Labels: 🔨 fix

#356 hotfix : inapp browser kakaotalk, line제외 삭제
  src/app/InApp.tsx
Labels: 🔨 fix

#357 [Feat] mixpanel#335
  src/app/create/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/PhotoUpload.tsx
  src/services/mixpanel.ts
Labels: ✨ feature
