Repository RollingPaper42/Front-End, pull requests merged in 2023-11, with the labels that each got.

#5 [Feat] 스트링캣 화면 뷰 테스트 개발
  package-lock.json
  package.json
  postcss.config.js
  prettier.config.js
  src/app/api/text/data.json
  src/app/api/text/route.ts
  src/app/page.tsx
  src/component/ObserveComponent.tsx
  src/types/content.ts
Labels: ✨ feature

#7 [Feat] : 모바일 뷰 레이아웃 설정 #6
  src/app/layout.tsx
Labels: ✨ feature

#13 [Feat] axiosInstance 생성
  src/utils/axios.ts
Labels: ✨ feature

#14 [fix] next build 에러
  src/app/page.tsx
Labels: 🐞 bug, 🔨 fix

#25 [Chore] : pull-request template 변경
  .github/pull_request_template.md
Labels: ⚙️ chore

#17 [Feat] 글작성 페이지 1차 구현
  src/app/add/page.tsx
  src/hooks/useInput.tsx
  src/types/id.ts
Labels: ✨ feature

#22 [Feat]메인, 로그인, 개별 스트링캣 페이지 1차 구현
  public/Google.png
  public/fonts/FiraCode-Regular.ttf
  public/kakao.png
  public/strcatImage.png
  src/app/create/page.tsx
  src/app/globals.css
  src/app/login/page.tsx
  src/app/page.tsx
  src/component/StrcatHeader.tsx
  tailwind.config.js
Labels: ✨ feature

#23 [Feat] strcat 상세페이지 1차 구현
  src/app/api/personal/data.json
  src/app/api/personal/route.ts
  src/app/api/text/data.json
  src/app/personal/[id]/page.tsx
  src/component/ObserveComponent.tsx
  src/component/StrcatComponent.tsx
  src/types/content.ts
Labels: ✨ feature

#21 [Feat] 모달 구현
  src/app/layout.tsx
  src/app/modal/page.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/Modal/index.tsx
  src/recoil/modal.ts
  src/types/modalComponent.ts
  src/utils/confirm.ts
Labels: ✨ feature

#29 bug/build시 에러 발생 해결#28
  src/app/create/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
Labels: 🐞 bug, 🔨 fix

#30 feat/메인 버튼 생성#27
  public/LoginButton.png
  public/StrcatHeader.png
  src/component/StrcatHeader.tsx
Labels: ✨ feature

#38 feat: BottomButton 생성
  src/component/BottomButton.tsx
Labels: ✨ feature

#40 [Feat] : add 페이지를 component로 변경
  src/app/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Add.tsx
  src/component/StrcatComponent.tsx
Labels: ✨ feature, 🎨 style

#43 [Feat] cat animation#18
  public/cats/strcat_basic_default.gif
  public/cats/strcat_black.gif
  public/cats/strcat_scroll_default.gif
  public/cats/strcat_yellow.gif
  src/app/modal/page.tsx
  src/app/page.tsx
  src/component/CatAnimation.tsx
  src/hooks/useAnimation.ts
  src/hooks/useModal.ts
  src/recoil/cat.ts
  src/types/cat.ts
Labels: ✨ feature

#42 feat/create page#33
  public/ActivateButton.png
  public/BackPage.png
  public/CalmButton.png
  public/CyanButton.png
  public/DisabledButton.png
  public/StrcatButton.png
  public/greenButton.png
  src/app/add/page.tsx
  src/app/create/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/component/ThemeChange.tsx
  src/recoil/theme.ts
  tailwind.config.js
Labels: ✨ feature

#41 [Feat] 그룹페이지 생성 및 사진뷰 추가, from 태그 추가
  public/mario.png
  src/app/add/page.tsx
  src/app/api/group/data.json
  src/app/api/group/route.ts
  src/app/api/personal/data.json
  src/app/group/[id]/page.tsx
  src/app/login/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Modal/Photo.tsx
  src/component/Modal/index.tsx
  src/component/ObserveComponent.tsx
  src/component/PhotoComponent.tsx
  src/component/StrcatComponent.tsx
  src/recoil/observe.ts
  src/types/boards.ts
  src/types/content.ts
  tailwind.config.js
Labels: ✨ feature

#44 [Fix] 백엔드 연결테스트
  src/app/create/page.tsx
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Add.tsx
  src/component/Modal/index.tsx
  src/component/PhotoComponent.tsx
  src/component/StrcatComponent.tsx
  src/utils/axios.ts
Labels: 🔨 fix

#47 [Feat] Header & Drawer 구현
  public/CheckSmall.svg
  public/ListDownButton.svg
  public/ListUpButton.svg
  public/LogoutIcon.svg
  public/NotifyIcon.svg
  public/ProfileImg.svg
  public/StrCatIcon.svg
  public/VersionIcon.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/component/Drawer.tsx
  src/component/StrcatHeader.tsx
  src/recoil/drawer.ts
Labels: ✨ feature, 🎨 style

#49 [Refactor] Drawer component분리 & [Style] Header Drawer design반영
  public/LoginButton.png
  public/LoginButton.svg
  public/Logo.svg
  public/StrcatHeader.png
  src/app/group/[id]/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Drawer.tsx
  src/component/DrawerItem.tsx
  src/component/DropListItem.tsx
  src/component/StrcatHeader.tsx
Labels: ✨ feature, ♻️ refactor, 🎨 style

#52 [feat] strcat조회페이지 리렌더링, 스크롤이벤트 오류수정, css적용
  src/app/api/login/route.ts
  src/app/api/personal/data.json
  src/app/api/users/data.json
  src/app/api/users/route.ts
  src/app/group/[id]/page.tsx
  src/app/layout.tsx
  src/app/personal/[id]/page.tsx
  src/component/ContentPhoto.tsx
  src/component/Drawer.tsx
  src/component/ObserveComponent.tsx
  src/component/ObserveContent.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatComponent.tsx
  src/component/StrcatHeader.tsx
  tailwind.config.js
Labels: 🔨 fix, ✨ feature

#57 feat/Create_page 모달 적용#51
  src/app/create/page.tsx
  src/app/login/page.tsx
Labels: ✨ feature

#64 [Bug] 무한리렌더링 에러수정 #62
  src/component/ContentPhoto.tsx
  src/component/Modal/Photo.tsx
  src/component/ObserveContent.tsx
  src/recoil/observe.ts
Labels: 🐞 bug, 🎨 style

#65 [Fix] Drawer & Header 오류 수정
  src/app/layout.tsx
  src/component/Drawer.tsx
  src/component/StrcatHeader.tsx
Labels: 🔨 fix, 🎨 style

#73 feat: strcat 테마별 색상 tailwind 적용#72
  tailwind.config.js
Labels: ✨ feature

#68 [Feat] strcat export#20
  package-lock.json
  package.json
  src/app/group/[id]/export/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/component/Modal/ExportSuccess.tsx
  src/component/export/Default.tsx
  src/component/export/ExportBoard.tsx
  src/component/export/ExportTheme.tsx
  src/component/export/LineBreak.tsx
  src/component/export/Writer.tsx
  src/types/export.ts
Labels: ✨ feature

#75 [Fix]npm run build error 수정
  src/component/export/Writer.tsx
Labels: 🐞 bug, 🔨 fix

#78 style: 전역 recoil 스타일 적용 #77
  src/app/create/page.tsx
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/ObserveContent.tsx
  src/component/StrcatBoard.tsx
  src/component/ThemeChange.tsx
  src/recoil/theme.ts
Labels: ✨ feature, 🎨 style

#71 [Feat] axios response interceptor#70
  src/app/api/error/data.json
  src/app/api/error/route.ts
  src/app/layout.tsx
  src/app/modal/page.tsx
  src/component/AxiosInterceptor.tsx
  src/hooks/useInterceptor.tsx
  src/utils/axios.ts
Labels: ✨ feature

#76 [feat] button 스타일적용, 그룹페이지 버튼 적용
  src/app/api/group/data.json
  src/app/api/personal/data.json
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Add.tsx
  src/component/BottomButton.tsx
  src/component/ContentPhoto.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatGroupTitle.tsx
  src/recoil/theme.ts
  src/types/boards.ts
  src/utils/scrollTo.ts
  tailwind.config.js
Labels: ✨ feature

#81 (KAN-50)feat/mainpage design apply 및 tailwind 오타 수정#63
  public/ActivateButton.png
  public/DisabledButton.png
  public/strcatImage.png
  src/app/page.tsx
  tailwind.config.js
Labels: ✨ feature

#80 feat/login checker#79
  src/app/login/check/page.tsx
  src/app/login/page.tsx
  src/component/StrcatHeader.tsx
  src/hooks/useInterceptor.tsx
  src/hooks/useLogin.ts
  src/recoil/login.ts
Labels: 🔨 fix, ✨ feature

#87 [HOT FIX] : drawer에서 호출하는 api로 인해 login으로 가는 버그 해결
  src/component/Drawer.tsx
  src/component/Modal/index.tsx
  src/utils/handleBackground.tsx
Labels: 🔨 fix

#82 (KAN-51)feat/summary page 디자인 적용#69
  src/app/summary/page.tsx
Labels: ✨ feature

#88 [feat] 조회페이지 버튼 기능추가, bottombutton 수정, 그룹조회페이지 observe에 따른 테마 변경 등
  src/app/api/personal/data.json
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Add.tsx
  src/component/BottomButton.tsx
  src/component/Icon/GroupCat.tsx
  src/component/Icon/ShortCut.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatGroupTitle.tsx
Labels: ✨ feature

#90 [Feat] : add #59 & [FIX] : npm run build 오류 수정
  package.json
  src/app/create/page.tsx
  src/app/group/[id]/page.tsx
  src/app/login/check/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/summary/page.tsx
  src/component/Add.tsx
  src/component/ContentPhoto.tsx
  src/component/PhotoUpload.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatHeader.tsx
Labels: ✨ feature

#96 [Feat] group create 페이지 구현 #92
  src/app/create/group/page.tsx
Labels: ✨ feature

#97 feat/로그인 페이지 디자인 적용#95
  src/app/login/page.tsx
Labels: ✨ feature

#99 [Style] layout의 스타일 적용 및 사용하지 않는 파일 삭제
  public/LoginButton_strcat.svg
  public/Logo_strcat.svg
  public/ProfileImg_strcat.svg
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/summary/page.tsx
  src/component/Add.tsx
  src/component/BottomButton.tsx
  src/component/Drawer.tsx
  src/component/Icon/Logo.tsx
  src/component/Icon/ProfileImg.tsx
  src/component/Modal/index.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatHeader.tsx
  src/recoil/atom.ts
  src/recoil/state.ts
  src/types/id.ts
Labels: 🧹 cleanup, 🎨 style

#105 (kan 65)feat/summary group avatar#102
  src/app/group/[id]/summary/page.tsx
Labels: ✨ feature

#106 (KAN-60)feat/summary path fix#94
  src/app/personal/[id]/summary/page.tsx
Labels: ✨ feature

#104 [Feat] login route#85
  package-lock.json
  src/app/login/check/page.tsx
  src/app/page.tsx
  src/component/StrcatHeader.tsx
  src/hooks/useInterceptor.tsx
Labels: ✨ feature

#107 (kan 59)feat/create page setlink#93
  src/app/create/page.tsx
Labels: ✨ feature

#103 [Fix] strcat 조회페이지에서 content가 없을때 add 불가능 에러 수정
  src/app/api/group/data.json
  src/app/api/personal/data.json
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/StrcatBoard.tsx
  src/types/boards.ts
Labels: 🐞 bug

#111 feat/page height 조절 및 backbutton router 수정 및 그룹 페이지 수정#108
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/app/personal/[id]/summary/page.tsx
Labels: ✨ feature

#114 feat/summary페이지 backbutton 구현#113
  src/app/group/[id]/summary/page.tsx
  src/app/personal/[id]/summary/page.tsx
Labels: ✨ feature

#116 [feat] 공유하기 기능 #112
  src/app/api/personal/data.json
  src/app/personal/[id]/page.tsx
  src/utils/handleShare.ts
Labels: ✨ feature

#118 [Feat] 메인 페이지 로그인 버튼 텍스트 정렬#117
  src/app/page.tsx
Labels: ✨ feature

#120 [Feat] svg를 이미지 파일에서 react component로 변경
  public/CheckSmall.svg
  public/ListDownButton.svg
  public/ListUpButton.svg
  public/Logo_strcat.svg
  public/LogoutIcon.svg
  public/ProfileImg_strcat.svg
  public/StrCatIcon.svg
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/app/group/[id]/page.tsx
  src/app/group/[id]/summary/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/Drawer.tsx
  src/component/DrawerItem.tsx
  src/component/DropListItem.tsx
  src/component/Icon/Back.tsx
  src/component/Icon/Drawer.tsx
  src/component/Icon/GroupCat.tsx
  src/component/Icon/Header.tsx
  src/component/Icon/LongCat.tsx
  src/component/Icon/ProfileImg.tsx
  src/component/Icon/ShortCut.tsx
  src/component/Icon/Strcat.tsx
  src/component/Icon/Theme.tsx
  src/component/Icon/drawer/Check.tsx
  src/component/Icon/drawer/DrawerProfileCat.tsx
  src/component/Icon/drawer/DropListDown.tsx
  src/component/Icon/drawer/DropListUp.tsx
  src/component/Icon/drawer/Logout.tsx
  src/component/Icon/header/HeaderProfileCat.tsx
  src/component/Icon/header/LogoCat.tsx
  src/component/Icon/header/Outline.tsx
  src/component/Icon/themeSelect/ThemeCalm.tsx
  src/component/Icon/themeSelect/ThemeCyan.tsx
  src/component/Icon/themeSelect/ThemeGreen.tsx
  src/component/Icon/themeSelect/ThemeStrcat.tsx
  src/component/StrcatGroupTitle.tsx
  src/component/StrcatHeader.tsx
  src/recoil/catTheme.ts
  src/recoil/theme.ts
  src/utils/handleBackground.tsx
  tailwind.config.js
Labels: ✨ feature

#124 feat/comma추가#119
  src/app/group/[id]/summary/page.tsx
  src/app/personal/[id]/summary/page.tsx
Labels: ✨ feature

#126 feat/summary페이지 share 기능 추가#125
  src/app/group/[id]/summary/page.tsx
  src/app/personal/[id]/summary/page.tsx
Labels: ✨ feature

#128 [Feat] confirm 모달 디자인 적용
  src/component/Icon/ModalBackground.tsx
  src/component/Icon/ModalClose.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/index.tsx
Labels: ✨ feature

#131 [Fix] boardId string으로 타입변경, data값 없을때 personal페이지 안보이는 에러 수정
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/ObserveContent.tsx
  src/component/ShareButton.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatGroupTitle.tsx
  src/recoil/observe.ts
  src/types/boards.ts
  src/utils/scrollTo.ts
Labels: 🔨 fix

#132 [fix]svg로 수정 및 버튼 css 조정#130
  public/ActivateButton.png
  public/BackPage.png
  public/CalmButton.png
  public/CyanButton.png
  public/DisabledButton.png
  public/Google.png
  public/Google.svg
  public/GroupStrcatMake.png
  public/StrcatButton.png
  public/StrcatMake.png
  public/greenButton.png
  public/kakao.png
  public/kakao.svg
  public/strcatImage.png
  src/app/create/page.tsx
  src/app/login/page.tsx
  src/component/ThemeChange.tsx
Labels: 🔨 fix

#134 [fix]ios 주석 표시#133
  src/app/page.tsx
Labels: 🔨 fix

#137 [Fix]create 페이지 API title에 주석 추가 및 textarea css 수정#135
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/component/ThemeChange.tsx
Labels: 🔨 fix

#136 [Feat] cat animation#18
  public/cats/calm/in.gif
  public/cats/calm/leftWall.gif
  public/cats/calm/out.gif
  public/cats/calm/rightWall.gif
  public/cats/calm/sit.gif
  public/cats/cyan/in.gif
  public/cats/cyan/leftWall.gif
  public/cats/cyan/out.gif
  public/cats/cyan/rightWall.gif
  public/cats/cyan/sit.gif
  public/cats/green/in.gif
  public/cats/green/leftWall.gif
  public/cats/green/out.gif
  public/cats/green/rightWall.gif
  public/cats/green/sit.gif
  public/cats/strcat/in.gif
  public/cats/strcat/leftWall.gif
  public/cats/strcat/out.gif
  public/cats/strcat/rightWall.gif
  public/cats/strcat/sit.gif
  public/cats/strcat_basic_default.gif
  public/cats/strcat_black.gif
  public/cats/strcat_scroll_default.gif
  public/cats/strcat_yellow.gif
  src/app/modal/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/CatAnimation.tsx
  src/component/StrcatHeader.tsx
  src/hooks/useAnimation.ts
  src/hooks/useCat.ts
  src/recoil/cat.ts
  src/recoil/catAnimation.ts
  src/recoil/state.ts
  src/types/animation.ts
  src/types/cat.ts
Labels: ✨ feature

#142 [Style] add컴포넌트 디자인 2차반영
  public/Delete.svg
  public/Picture.svg
  src/app/create/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Add.tsx
  src/component/BottomButton.tsx
  src/component/ContentPhoto.tsx
  src/component/ObserveContent.tsx
  src/component/PhotoUpload.tsx
  src/component/PreviewPhoto.tsx
  src/hooks/useInterceptor.tsx
  src/types/content.ts
Labels: 🔨 fix, 🎨 style

#140 [Feat] strcat 조회페이지 디자인 적용
  src/app/api/group/data.json
  src/app/api/personal/data.json
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/BottomButton.tsx
  src/component/Modal/Photo.tsx
  src/component/Modal/index.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/StrcatGroupTitle.tsx
  src/recoil/theme.ts
Labels: ✨ feature

#143 [Feat] drawer 로그아웃 기능추가
  src/component/Drawer.tsx
  src/component/StrcatHeader.tsx
Labels: 🔨 fix, ✨ feature

#145 [Fix] 조회페이지 통합테스트 1차 수정 #144
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Icon/Share.tsx
  src/component/Modal/Photo.tsx
  src/component/Modal/index.tsx
  src/component/ObserveContent.tsx
  src/component/ObserveTitle.tsx
  src/component/ShareButton.tsx
  src/component/StrcatBoard.tsx
Labels: 🔨 fix, 🎨 style

#147 [Fix]combine test dokoh#144
  src/app/create/page.tsx
  src/app/group/[id]/summary/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/Drawer.tsx
  src/component/Icon/LongCat.tsx
  src/component/Icon/ShortCut.tsx
  src/component/StrcatHeader.tsx
  src/hooks/useLogin.ts
Labels: 🔨 fix

#146 [Hot Fix!] : Combine Test 1차수정
  src/app/create/group/page.tsx
  src/app/create/page.tsx
  src/app/globals.css
  src/app/group/[id]/page.tsx
  src/app/login/check/page.tsx
  src/app/personal/[id]/page.tsx
  src/app/personal/[id]/summary/page.tsx
  src/component/Drawer.tsx
Labels: 🔨 fix, 🎨 style

#148 [Feat] export page data#144
  public/LoginButton_strcat.svg
  public/NotifyIcon.svg
  public/VersionIcon.svg
  public/mario.png
  public/next.svg
  public/vercel.svg
  src/app/create/page.tsx
  src/app/group/[id]/export/page.tsx
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/export/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/BottomButton.tsx
  src/component/Icon/Header.tsx
  src/component/Icon/ShortCut.tsx
  src/component/Icon/header/LogoText.tsx
  src/component/StrcatHeader.tsx
  src/component/export/Default.tsx
  src/component/export/ExportBoard.tsx
  src/component/export/LineBreak.tsx
  src/component/export/Writer.tsx
Labels: ✨ feature

#151 [Feat] NotFound Custom 페이지 생성
  public/NotFoundButton.svg
  public/NotFoundCat.svg
  src/app/not-found.tsx
Labels: ✨ feature

#152 [Fix]cat animation bug#144
  src/app/group/[id]/page.tsx
  src/app/modal/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/CatAnimation.tsx
  src/component/StrcatHeader.tsx
  src/hooks/useCat.ts
  src/recoil/catAnimation.ts
  src/types/animation.ts
Labels: 🐞 bug, 🔨 fix

#156 [Feat] : loading컴포넌트 생성 및 적용
  src/app/group/[id]/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Loading.tsx
  tailwind.config.js
Labels: ✨ feature

#157 [Hot Fix] : 자잘한 버그 수정 #144
  src/app/create/group/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Icon/Share.tsx
  src/component/StrcatBoard.tsx
Labels: 🔨 fix

#158 [feat/fix] 에러모달 디자인 적용 및 자잘한 에러수정
  src/app/group/[id]/page.tsx
  src/app/modal/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Icon/ModalErrorBackground.tsx
  src/component/Modal/Confirm.tsx
  src/component/Modal/Error.tsx
  src/component/ObserveTitle.tsx
  src/component/StrcatBoard.tsx
  src/component/StrcatGroupTitle.tsx
  src/hooks/useInterceptor.tsx
  src/recoil/theme.ts
Labels: 🔨 fix, ✨ feature

#160 [hotfix]로그인 버튼 css 조정 및 main 페이지 테마 적용#154
  src/app/login/page.tsx
  src/app/page.tsx
  src/recoil/theme.ts
  tailwind.config.js
Labels: 🔨 fix

#164 [fix]3rd test hotfix#163
  src/app/create/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/component/BottomButton.tsx
  src/component/ThemeChange.tsx
Labels: 🔨 fix
