Repository RollingPaper42/Front-End, pull requests merged in 2024-01, with the labels that each got.

#362 [Docs] : readme update
  README.md
Labels: 📖 docs

#364 [Feat] design 템플릿 생성
  .github/ISSUE_TEMPLATE/design-report.md
Labels: ✨ feature

#369 [Refactor] api interface화
  src/app/create/page.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Common/HeaderLayout/Drawer.tsx
  src/component/Personal/Summary.tsx
  src/hooks/useInterceptor.tsx
  src/hooks/useLogin.ts
  src/utils/apiInterface.tsx
Labels: ♻️ refactor

#368 [Refactor] toast 호출 방식 변경#367
  src/app/personal/[id]/page.tsx
Labels: ♻️ refactor

#376 [style] 테마 이미지 변경, personal 페이지 고양이 크기 변경
  public/create/chrisCat.svg
  public/create/masCat.svg
  src/component/Personal/BottomAnimationImage.tsx
Labels: 🎨 style

#378 [refactor] 데이터 코드 분리, 뷰 코드 리팩토링 #377
  src/app/personal/[id]/page.tsx
  src/component/Personal/FirstContent.tsx
Labels: ♻️ refactor
