Repository RollingPaper42/Front-End, pull requests merged in 2024-02, with the labels that each got.

#386 [Feat] OG 이미지 변경 #384
  public/OG.png
Labels: ✨ feature, 🎨 style

#381 [Feat] new year theme#379
  next.config.js
  public/cats/sul/sit.gif
  public/create/sulHat.svg
  public/preview/sul.png
  src/app/create/page.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Common/HeaderLayout/DefaultHeader.tsx
  src/component/Common/HeaderLayout/Drawer.tsx
  src/component/Common/HeaderLayout/TitleHeader.tsx
  src/component/Common/Icon/PhotoPreview.tsx
  src/component/Common/Modal/Confirm.tsx
  src/component/Common/Modal/Error.tsx
  src/component/Common/Modal/PhotoModal.tsx
  src/component/Common/ObserveContent.tsx
  src/component/Common/StrcatBoard.tsx
  src/component/Create/CreateTheme.tsx
  src/component/Create/PreviewTheme.tsx
  src/component/Create/SelectButton.tsx
  src/component/Create/ThemeSelect.tsx
  src/component/MainManStrcat.tsx
  src/recoil/addContent.ts
  src/recoil/content.ts
  src/recoil/state.ts
  src/recoil/theme.ts
  src/types/boards.ts
  src/types/mixpanel.ts
  src/types/theme.ts
  src/utils/theme/bgTheme.ts
  src/utils/theme/default.ts
  src/utils/theme/textTheme.ts
  tailwind.config.js
Labels: ✨ feature, ♻️ refactor

#389 [Feat] contents 편집
  public/personal/checkboxTrue.svg
  src/app/create/page.tsx
  src/app/personal/[id]/add/page.tsx
  src/app/personal/[id]/page.tsx
  src/component/Common/Modal/Introduce.tsx
  src/component/Common/Modal/PhotoModal.tsx
  src/component/Common/ObserveContent.tsx
  src/component/Common/StrcatBoard.tsx
  src/component/Personal/Add/PhotoUpload.tsx
  src/component/Personal/OwnerButtonLayer.tsx
  src/hooks/useInterceptor.tsx
  src/utils/apiInterface.tsx
Labels: 🐞 bug, ✨ feature
